// flow-typed signature: 42f632707cb27e8ecd8cf6b1e48ba5a5
// flow-typed version: <<STUB>>/precise-commits_v^1.0.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'precise-commits'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'precise-commits' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'precise-commits/bin/index' {
  declare module.exports: any;
}

declare module 'precise-commits/lib/git-utils' {
  declare module.exports: any;
}

declare module 'precise-commits/lib/index' {
  declare module.exports: any;
}

declare module 'precise-commits/lib/modified-file' {
  declare module.exports: any;
}

declare module 'precise-commits/lib/precise-formatter' {
  declare module.exports: any;
}

declare module 'precise-commits/lib/precise-formatters/prettier' {
  declare module.exports: any;
}

declare module 'precise-commits/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'precise-commits/bin/index.js' {
  declare module.exports: $Exports<'precise-commits/bin/index'>;
}
declare module 'precise-commits/lib/git-utils.js' {
  declare module.exports: $Exports<'precise-commits/lib/git-utils'>;
}
declare module 'precise-commits/lib/index.js' {
  declare module.exports: $Exports<'precise-commits/lib/index'>;
}
declare module 'precise-commits/lib/modified-file.js' {
  declare module.exports: $Exports<'precise-commits/lib/modified-file'>;
}
declare module 'precise-commits/lib/precise-formatter.js' {
  declare module.exports: $Exports<'precise-commits/lib/precise-formatter'>;
}
declare module 'precise-commits/lib/precise-formatters/prettier.js' {
  declare module.exports: $Exports<'precise-commits/lib/precise-formatters/prettier'>;
}
declare module 'precise-commits/lib/utils.js' {
  declare module.exports: $Exports<'precise-commits/lib/utils'>;
}
