// flow-typed signature: 93d2814ea1635f57301edca7b685e806
// flow-typed version: <<STUB>>/rc-checkbox_v^2.1.6/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-checkbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-checkbox/es/Checkbox' {
  declare module.exports: any;
}

declare module 'rc-checkbox/es/index' {
  declare module.exports: any;
}

declare module 'rc-checkbox/lib/Checkbox' {
  declare module.exports: any;
}

declare module 'rc-checkbox/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-checkbox/es/Checkbox.js' {
  declare module.exports: $Exports<'rc-checkbox/es/Checkbox'>;
}
declare module 'rc-checkbox/es/index.js' {
  declare module.exports: $Exports<'rc-checkbox/es/index'>;
}
declare module 'rc-checkbox/lib/Checkbox.js' {
  declare module.exports: $Exports<'rc-checkbox/lib/Checkbox'>;
}
declare module 'rc-checkbox/lib/index.js' {
  declare module.exports: $Exports<'rc-checkbox/lib/index'>;
}
