// flow-typed signature: 987617ab06c32c931b90e75749472bfd
// flow-typed version: <<STUB>>/react-idle-timer_v^4.2.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-idle-timer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-idle-timer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-idle-timer/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-idle-timer/dist/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-idle-timer/dist/index.es.js' {
  declare module.exports: $Exports<'react-idle-timer/dist/index.es'>;
}
declare module 'react-idle-timer/dist/index.min.js' {
  declare module.exports: $Exports<'react-idle-timer/dist/index.min'>;
}
