// flow-typed signature: 152341243f850be7e1bda518d46a9fbf
// flow-typed version: <<STUB>>/stanza.io_v^9.0.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stanza.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stanza.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stanza.io/lib/client' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/attention' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/avatar' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/bind' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/blocking' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/bob' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/bookmarks' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/bosh' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/carbons' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/chatstates' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/command' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/correction' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/csi' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/dataforms' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/delayed' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/disco' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/escaping' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/extdisco' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/features' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/forwarding' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/geoloc' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/hashes' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/idle' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/invisible' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/jidprep' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/jingle' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/json' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/keepalive' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/logging' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/mam' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/mood' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/muc' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/nick' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/oldwebsocket' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/oob' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/ping' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/private' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/psa' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/pubsub' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/reach' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/receipts' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/references' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/register' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/roster' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/rtt' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/sasl' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/session' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/shim' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/smacks' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/time' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/tune' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/vcard' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/version' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/plugins/websocket' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/sm' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/transports/bosh' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/transports/old-websocket' {
  declare module.exports: any;
}

declare module 'stanza.io/lib/transports/websocket' {
  declare module.exports: any;
}

declare module 'stanza.io/test/connection' {
  declare module.exports: any;
}

declare module 'stanza.io/test/index' {
  declare module.exports: any;
}

declare module 'stanza.io/test/stanza-dataforms' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stanza.io/index' {
  declare module.exports: $Exports<'stanza.io'>;
}
declare module 'stanza.io/index.js' {
  declare module.exports: $Exports<'stanza.io'>;
}
declare module 'stanza.io/lib/client.js' {
  declare module.exports: $Exports<'stanza.io/lib/client'>;
}
declare module 'stanza.io/lib/plugins/attention.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/attention'>;
}
declare module 'stanza.io/lib/plugins/avatar.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/avatar'>;
}
declare module 'stanza.io/lib/plugins/bind.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/bind'>;
}
declare module 'stanza.io/lib/plugins/blocking.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/blocking'>;
}
declare module 'stanza.io/lib/plugins/bob.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/bob'>;
}
declare module 'stanza.io/lib/plugins/bookmarks.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/bookmarks'>;
}
declare module 'stanza.io/lib/plugins/bosh.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/bosh'>;
}
declare module 'stanza.io/lib/plugins/carbons.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/carbons'>;
}
declare module 'stanza.io/lib/plugins/chatstates.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/chatstates'>;
}
declare module 'stanza.io/lib/plugins/command.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/command'>;
}
declare module 'stanza.io/lib/plugins/correction.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/correction'>;
}
declare module 'stanza.io/lib/plugins/csi.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/csi'>;
}
declare module 'stanza.io/lib/plugins/dataforms.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/dataforms'>;
}
declare module 'stanza.io/lib/plugins/delayed.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/delayed'>;
}
declare module 'stanza.io/lib/plugins/disco.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/disco'>;
}
declare module 'stanza.io/lib/plugins/escaping.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/escaping'>;
}
declare module 'stanza.io/lib/plugins/extdisco.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/extdisco'>;
}
declare module 'stanza.io/lib/plugins/features.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/features'>;
}
declare module 'stanza.io/lib/plugins/forwarding.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/forwarding'>;
}
declare module 'stanza.io/lib/plugins/geoloc.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/geoloc'>;
}
declare module 'stanza.io/lib/plugins/hashes.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/hashes'>;
}
declare module 'stanza.io/lib/plugins/idle.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/idle'>;
}
declare module 'stanza.io/lib/plugins/index.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/index'>;
}
declare module 'stanza.io/lib/plugins/invisible.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/invisible'>;
}
declare module 'stanza.io/lib/plugins/jidprep.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/jidprep'>;
}
declare module 'stanza.io/lib/plugins/jingle.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/jingle'>;
}
declare module 'stanza.io/lib/plugins/json.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/json'>;
}
declare module 'stanza.io/lib/plugins/keepalive.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/keepalive'>;
}
declare module 'stanza.io/lib/plugins/logging.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/logging'>;
}
declare module 'stanza.io/lib/plugins/mam.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/mam'>;
}
declare module 'stanza.io/lib/plugins/mood.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/mood'>;
}
declare module 'stanza.io/lib/plugins/muc.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/muc'>;
}
declare module 'stanza.io/lib/plugins/nick.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/nick'>;
}
declare module 'stanza.io/lib/plugins/oldwebsocket.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/oldwebsocket'>;
}
declare module 'stanza.io/lib/plugins/oob.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/oob'>;
}
declare module 'stanza.io/lib/plugins/ping.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/ping'>;
}
declare module 'stanza.io/lib/plugins/private.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/private'>;
}
declare module 'stanza.io/lib/plugins/psa.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/psa'>;
}
declare module 'stanza.io/lib/plugins/pubsub.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/pubsub'>;
}
declare module 'stanza.io/lib/plugins/reach.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/reach'>;
}
declare module 'stanza.io/lib/plugins/receipts.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/receipts'>;
}
declare module 'stanza.io/lib/plugins/references.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/references'>;
}
declare module 'stanza.io/lib/plugins/register.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/register'>;
}
declare module 'stanza.io/lib/plugins/roster.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/roster'>;
}
declare module 'stanza.io/lib/plugins/rtt.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/rtt'>;
}
declare module 'stanza.io/lib/plugins/sasl.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/sasl'>;
}
declare module 'stanza.io/lib/plugins/session.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/session'>;
}
declare module 'stanza.io/lib/plugins/shim.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/shim'>;
}
declare module 'stanza.io/lib/plugins/smacks.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/smacks'>;
}
declare module 'stanza.io/lib/plugins/time.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/time'>;
}
declare module 'stanza.io/lib/plugins/tune.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/tune'>;
}
declare module 'stanza.io/lib/plugins/vcard.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/vcard'>;
}
declare module 'stanza.io/lib/plugins/version.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/version'>;
}
declare module 'stanza.io/lib/plugins/websocket.js' {
  declare module.exports: $Exports<'stanza.io/lib/plugins/websocket'>;
}
declare module 'stanza.io/lib/sm.js' {
  declare module.exports: $Exports<'stanza.io/lib/sm'>;
}
declare module 'stanza.io/lib/transports/bosh.js' {
  declare module.exports: $Exports<'stanza.io/lib/transports/bosh'>;
}
declare module 'stanza.io/lib/transports/old-websocket.js' {
  declare module.exports: $Exports<'stanza.io/lib/transports/old-websocket'>;
}
declare module 'stanza.io/lib/transports/websocket.js' {
  declare module.exports: $Exports<'stanza.io/lib/transports/websocket'>;
}
declare module 'stanza.io/test/connection.js' {
  declare module.exports: $Exports<'stanza.io/test/connection'>;
}
declare module 'stanza.io/test/index.js' {
  declare module.exports: $Exports<'stanza.io/test/index'>;
}
declare module 'stanza.io/test/stanza-dataforms.js' {
  declare module.exports: $Exports<'stanza.io/test/stanza-dataforms'>;
}
